cosmology:
  h: 0.674
  Omega_m: 0.315
  n_s: 0.965
  sigma8: 0.811
paths:
  kids_binA_clean: data/processed/lensing/DeltaSigma_binA_clean.csv
  routeA_1h_binA: data/processed/routeA/routeA_m0p18_binA.csv
  p_nl: data/raw/hmcode/Pnl_z0p286_HMcode.csv
  kids_binB_clean: data/processed/lensing/DeltaSigma_binB_clean.csv
  routeA_1h_binB: data/processed/routeA/realRouteA_m018_binB_total.csv
  kids_binC_clean: data/processed/lensing/DeltaSigma_binC_clean.csv
  routeA_1h_binC: data/processed/routeA/HMcode_routeA_m018_binC_A1_total.csv
  kids_binLOWZ_clean: data/processed/lensing/LOWZ_clean.csv
  kids_binCMASS_clean: data/processed/lensing/CMASS_clean.csv
  routeA_1h_binLOWZ: data/processed/routeA/routeA_m0p18_binA.csv
  routeA_1h_binCMASS: data/processed/routeA/routeA_m0p18_binA.csv
fitting:
  k_min: 0.0001
  k_max: 30.0
  n_k: 2048
  initial:
    A1h: 1.0
    b0: 1.6
    b2: 10.0
    lam: 1.1
  bounds:
    A1h:
    - 0.0
    - 2000.0
    b0:
    - 0.5
    - 3.0
    b2:
    - 0.0
    - 50.0
    lam:
    - 0.05
    - 5.0
